/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package wineMateLogin;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum FindPasswordStatus implements org.apache.thrift.TEnum {
  PW_SUCCESS(0),
  PW_FAILED(1);

  private final int value;

  private FindPasswordStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FindPasswordStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return PW_SUCCESS;
      case 1:
        return PW_FAILED;
      default:
        return null;
    }
  }
}
