/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package wineMateLogin;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RegistrationStatus implements org.apache.thrift.TEnum {
  REGISTRATION_SUCCESS(0),
  REGISTRATION_DUPLICATE_USERNAME(1),
  REGISTRATION_DUPLICATE_EMAIL(2);

  private final int value;

  private RegistrationStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RegistrationStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return REGISTRATION_SUCCESS;
      case 1:
        return REGISTRATION_DUPLICATE_USERNAME;
      case 2:
        return REGISTRATION_DUPLICATE_EMAIL;
      default:
        return null;
    }
  }
}
